"""Add an index to the stem property of Word

Revision ID: 76fd231f76bc
Revises: b4f66986a000
Create Date: 2020-10-16 15:23:12.364110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fd231f76bc'
down_revision = 'b4f66986a000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_word_stem'), 'word', ['stem'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_stem'), table_name='word')
    # ### end Alembic commands ###
