"""Add description to Page

Revision ID: b4f66986a000
Revises: a9422f5dde7c
Create Date: 2020-10-16 15:11:11.731468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f66986a000'
down_revision = 'a9422f5dde7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'description')
    # ### end Alembic commands ###
